### ISSUE TITLE
Browser simulation of ArrayEquations.ChemicalReactions

### ISSUE THREAD

**Issue by tbeu** [xogeny/ModelicaBook#100]
The models of http://beta.book.xogeny.com/behavior/arrays/chem/ have a scaled output of Cx_50 in the static plot. The dynamic plot looks different for Cx but Cx_50 is still in the legend.

**Comment by xogeny** [comment]
I think the case data actually has a scale factor here that can be used.  That would be simpler since it wouldn't involve more variables, hiding results, etc.

**Comment by xogeny** [comment]
Done.  Now using case data scale factor for each variable.
