### ISSUE TITLE
Plotting  CC1_Q raises an exception

### ISSUE THREAD

**Issue by dietmarw** [xogeny/ModelicaBook#104]
```
/ModelicaBook/text/source/behavior/discrete/hysteresis.rst:31: WARNING: Exception occurred in plotting CC1_Q
...
OverflowError: Allocated too many blocks
```

Looks like this is an issue of to many points being plotted. See also http://stackoverflow.com/questions/20330475/matplotlib-overflowerror-allocated-too-many-blocks

**Comment by dietmarw** [comment]
This seems no longer to be an issue. At least the plot is generated. There is no interactive simulation for this case though. Probably on purpose, @mtiller ?

**Comment by xogeny** [comment]
I've removed interactivity for `CC1` and `CC1_Q` because they chatter and will give both client and server fits.
