### ISSUE TITLE
Fix assertion messages

### ISSUE THREAD

**Issue by tbeu** [xogeny/ModelicaBook#120]
There are several assertion messages that are mathematically not exact.
Where it reads

``` mo
assert(population>=0, "Population must be greater than zero");
```

it should read

``` mo
assert(population>=0, "Population must be greater than or equal to zero");
```

or

``` mo
assert(population>=0, "Population must not be less than zero");
```

Is this relevant?

**Comment by tbeu** [comment]
Same kind of inexact assertion message still in in InterpolateVector.mo.

**Comment by dietmarw** [comment]
I missed that it was in several places. So new PR will be coming up.
