### ISSUE TITLE
Header bar hides headlines when using jump marks

### ISSUE THREAD

**Issue by dietmarw** [xogeny/ModelicaBook#127]
When clicking on reference links the section header is always hidden behind the black header bar. This means that one does not immediately recognize where one just jumped to. 

Example: http://beta.book.xogeny.com/components/components/elec_comps/#electrical-components and tell what sections we are in.

**Comment by dietmarw** [comment]
Maybe a variant of this can be applied: http://stackoverflow.com/questions/4086107/html-positionfixed-page-header-and-in-page-anchors

**Comment by dietmarw** [comment]
@mtiller I've just checked and also the new react-based version is hiding the heading behind the head bar. Could you fix this at the same time?

**Comment by xogeny** [comment]
I noticed this as well.  Not sure what I can do though.  It has to do with how fixed headers are done.  Normally, you pad the top of the HTML body.  But the code that scrolls you to the anchor doesn't know what is hidden.  I will investigate to see if there are clever solutions.

**Comment by xogeny** [comment]
Found [several useful suggestions](https://stackoverflow.com/questions/10732690/offsetting-an-html-anchor-to-adjust-for-fixed-header).  Ideally, I'd use a pure CSS approach with selectors that pinpoint the issue.  So that will require more investigation.
