### ISSUE TITLE
Name of stiffness is c or k

### ISSUE THREAD

**Issue by tbeu** [xogeny/ModelicaBook#131]
In PlantWithPulseCounter.svg of http://beta.book.xogeny.com/behavior/equations/mechanical/ the springs use _c_ as variable name for their stiffness. However, later in text and models (e.g. SecondOrderSystem.mo) it is _k_.

**Comment by dietmarw** [comment]
I'd say the images is fine and the text (and models) should be adapted to use "c" for spring constant. This is also the parameter name in the MSL.

**Comment by xogeny** [comment]
Fixed a few more mistakes.  Pushed and building for `beta` right now.  Needs a final proof-read before I close this.

**Comment by xogeny** [comment]
Closing this.  It seems to be sorted out for all cases I'm aware of (including the interactive apps).  So if somebody finds more issues, they should either reopen this or create a new ticket.
