### ISSUE TITLE
search page

### ISSUE THREAD

**Issue by thorade** [xogeny/ModelicaBook#168]
For me, searching via the search page does not work or is very slow. 
It seems to be stuck at "Preparing search".
Compare e.g. speed of
http://book.xogeny.com/search/?q=Volterra
versus
https://www.google.de/search?q=Volterra+site%3Abook.xogeny.com

The search button or field might be placed more prominently, e.g. a field+button on every page

**Comment by xogeny** [comment]
FYI, I've added a true client-side search solution to the [beta](http://beta.book.xogeny.com) page.  When we push `0.5.0`, it will be available on the main site.  I'm going to leave this open because we should find a way to suppress generation of the search page (since it doesn't do anything...).

**Comment by thorade** [comment]
Great, thanks. On the beta page, the search page is just empty for me and the search box on the top of any page does not yet do anything, but I gues you are aware of that already.

**Comment by xogeny** [comment]
Yep.  Something to do with the CI build because it works locally.  I'll work on it this morning.  Hopefully it will be something simple.

**Comment by xogeny** [comment]
Now building properly and running on `beta`.  Closing this but also opening #374 because it includes some potential improvements (on top of what's been done here).
