### ISSUE TITLE
Fix plot generation scripts.

### ISSUE THREAD

**Issue by dietmarw** [xogeny/ModelicaBook#171]
Currently some of the plots are simply not generated because of errors in the generation scripts. Examples are:
- `../plots/CC1_Q.py`
- `../plots/SV1.py`
- `../plots/SV1U.py`
- `../plots/SV2.py`
- `../plots/SV2T.py`

**Comment by dietmarw** [comment]
I would say this is not just cosmetic because the text refers to something which is simply not presented.

**Comment by xogeny** [comment]
Still an issue?!?

**Comment by dietmarw** [comment]
Just tested it with my latest (updated) docker image (PR is coming) and it works there.
