### ISSUE TITLE
Function Annotations in the wrong place

### ISSUE THREAD

**Issue by xogeny** [xogeny/ModelicaBook#185]
Jesper Mattsson pointed out that since Modelica 3.2, function annotations must be at the end of the class definition.  The examples in the text (and probably in the library) should be adjusted accordingly.

**Comment by thorade** [comment]
Even since Modelica 3.1
https://www.modelica.org/news_items/release_of_modelica_3_1
Last section

**Comment by dietmarw** [comment]
To me it looks like that all annotations are already at the correct position. So this can possibly be closed.

**Comment by thorade** [comment]
Tools are allowed to move class level annotations to the end of the file and afaik Dymola does this automatically when opening a library (That was a problem with our library), but when saving all files with Dymola, git shows no changes, so I think Dietmar is right and all class level annotations already are in the correct place.

**Comment by dietmarw** [comment]
Yes that was exactly what I did in order to test for wrong annotation placement.
