### ISSUE TITLE
ideas for more examples

### ISSUE THREAD

**Issue by thorade** [xogeny/ModelicaBook#225]
There are some nice examples in the ODE section of the SciPy cookbook:
http://wiki.scipy.org/Cookbook
Some of these could be added in a future version of the book

**Comment by tbeu** [comment]
There are five sample cases listed
 1. Zombie Apocalypse ODE Modeling
 2. A coupled spring-mass system
 3. Lotka-Volterra Tutorial
 4. KdV
 5. Hastings and Powell food chain model

There already is 2. and 3. in the book. 4. is not in time domain. Thus 1. and 5 are left but I doubt they give different insight in Modelica than 3. already does. Systems of first-order ODEs is too similar, I guess.

**Comment by thorade** [comment]
The idea came too late anyway, I guess.
I'll just close this issue.
Thanks for taking the time to look at the listed examples.
