### ISSUE TITLE
Browser simulation fails in Google Chrome and Chromium

### ISSUE THREAD

**Issue by xie-dongping** [xogeny/ModelicaBook#233]
It works with the firefox versions that we tested. 

But simulation fails with both google chrome for windows and my chromium setup in ubuntu.

Chromium Version 41.0.2272.76 Ubuntu 14.04 (64-bit)

Error from 

http://book.xogeny.com/behavior/functions/controller/

```
xogeny.js:14 Whee! let's simulate model SIL!
xogeny.js:17 Creating worker for script at /_static/js/SIL.js
xogeny.js:87 Firing message to worker
xogeny.js:27 Message from worker: 
xogeny.js:28 MessageEvent {ports: Array[0], data: Object, source: null, lastEventId: "", origin: ""…}
xogeny.js:34 Got preload message
xogeny.js:35 Starting simulation
xogeny.js:55 Run command sent to worker:
xogeny.js:56 Object {basename: "SIL", override: Object}
xogeny.js:59 Simulation status: undefined
jquery.csv-0.71.min.js:12 Uncaught TypeError: Cannot read property 'replace' of undefinedjquery.csv-0.71.min.js:12 $.csv.parsers.parsejquery.csv-0.71.min.js:63 $.csv.toArraysxogeny.js:60 (anonymous function)
xogeny.js:27 Message from worker: 
xogeny.js:28 MessageEvent {ports: Array[0], data: Object, source: null, lastEventId: "", origin: ""…}
xogeny.js:59 Simulation status: Simulation finished
```

**Comment by dietmarw** [comment]
I can confirm that this problem also exists with Google Chrome Version 42.0.2311.60 beta (64-bit) on Ubuntu 14.10.

**Comment by tbeu** [comment]
This issue label can be set to Browser simulation.

**Comment by dietmarw** [comment]
Just tested on Chrome for linux: Version 49.0.2623.87 (64-bit) and it works fine. @xie-dongping could you check if this issue still exists?

**Comment by pierre-haessig** [comment]
I've tested the [Lotka-Volterra System](http://book.xogeny.com/behavior/equations/population/) with Chromium 59 under Debian 9 (Stretch). It works fine. 

Since the first report is 2.5 years old and because all browsers have been changing much since that, I  recommend closing this issue.

**Comment by dietmarw** [comment]
Agreed, also tested it on Ubuntu 16.04 and 17.10 (chromium, firefox) and not issue. 
@xie-dongping fine to close?

**Comment by xie-dongping** [comment]
Thanks @pierre-haessig @dietmarw for coming back to the issue :+1:
