### ISSUE TITLE
New option for sphinx build lets us choose "inline" or "footnote" links in PDF

### ISSUE THREAD

**Issue by dietmarw** [xogeny/ModelicaBook#235]
From Sphinx version 1.1 on (current is 1.3.1) the config setting `latex_show_urls` has changed from simply `True` or `False` to 
 * 'no' – do not display URLs (default)
 * 'footnote' – display URLs in footnotes
 * 'inline' – display URLs inline in parentheses
Before we had 'inline' as in:

![inline](https://cloud.githubusercontent.com/assets/9332/6921459/4903fe0e-d7c5-11e4-86f8-8d4f4c73d852.png)

But we could now also use the footnote option. Here the same passage with that option: 

![footnote](https://cloud.githubusercontent.com/assets/9332/6921470/5c424e30-d7c5-11e4-8571-43fc6900074d.png)

What should we go for?

**Comment by tbeu** [comment]
I'd prefer the new option. There is the link anyway in the text thus the visible URL can be moved to the footnote.

**Comment by dietmarw** [comment]
I agree but would like to let @mtiller decide.

**Comment by xogeny** [comment]
I definitely prefer the new option.  Make it so. :-)

**Comment by dietmarw** [comment]
Footnote engaged, Sir.
