### ISSUE TITLE
Default value of min/max attribute

### ISSUE THREAD

**Issue by tbeu** [xogeny/ModelicaBook#242]
It says in variables.rst that default value of the real-valued min/max attribute is -inf/+inf, respectively. But as Reals will generally be translated into floating point representations by a Modelica compiler it should it be -DBL_MAX/+DBL_MAX in case of double arithmetic (or similar). MLS 3.3 rev. 1 says in section 4.8.1 that defualt is -Inf/+Inf where Inf is a large number.

**Comment by xogeny** [comment]
Fixed in a recent commit.
