### ISSUE TITLE
Build and push the Chinese version to AWS

### ISSUE THREAD

**Issue by xie-dongping** [xogeny/ModelicaBook#250]
The Chinese translation is merged and therefore can be pushed to the offcial s3 bucket of Xogeny.

**Comment by xogeny** [comment]
Definitely!  Thanks for the nudge.

**Comment by xogeny** [comment]
You mean like this:

http://book.xogeny.com/cn

:-)

Note, when I view it I don't see titles on plots.  This could be related to my browser or locale.  So it would be good to review the content and determine how much of this is a general issue and not related to my specific OS/locale.

In any case, **amazing work**!

**Comment by xie-dongping** [comment]
Exactly what I mean, Mike. : )

And the problem with the plots has to do with the font (as they are prerendered images from your computer). It is sort of weird that you don't have "Droid Sans Fallback". 

Could you try if there's anything if you run
```bash
    fc-list :lang=zh-CN | grep Droid
```
If not and you are using a Debian-like, that this will do:
```bash
    sudo apt-get install -y fonts-droid
```
It that's not working, you can try changing the fonts for Chinese locale by editing the 
```bash
    vim text/source/_sphinxext/xogeny/locales.py
```
at line 19.

Let's see if it works.

**Comment by dietmarw** [comment]
I see the same issue with the interactive plots. I'm running Ubuntu 15.04 and have fonts-droid installed. But it doesn't seem to work. 
![screenshot from 2015-08-17 08 47 32](https://cloud.githubusercontent.com/assets/9332/9299489/b6279874-44bc-11e5-914b-576725c2ebf1.png)
What exactly do you suggest to change the Chinese locale to for testing?

**Comment by dietmarw** [comment]
Never mind. There was a misunderstanding on my side. So I rebuild the webversion on my machine and all the symbols get generated fine. Mike you might wanna rerun the build with the fonts-droid package installed.

**Comment by sjoelund** [comment]
谢谢

**Comment by xogeny** [comment]
My issue is, I'm building on a Mac and I don't know what is equivalent to `fonts-droid`.  Homebrew doesn't have it.

What would be really cool to have is to update the `Dockerfile` so that all the necessary build tools were installed, have the `CMD` be to push out a new version (based on GitHub) **and** allow the necessary Amazon environment variables to be passed in via the `-e` flag.  Then we could all work from a common image/build environment.

Unfortunately, I'm about to leave town and I'm not sure when I'd have time to do this anyway.  But, if somebody updated the Docker stuff to do this, I would totally use it.

Until then, I'll just have to hunt around for the right OSX fonts.

**Comment by xie-dongping** [comment]
The fastest solution for this problem is to install the Droid Sans Fallback font in OSX.

I extracted the DroidSansFallbackFull.ttf from https://packages.debian.org/sid/all/fonts-droid/download and uploaded it to http://s000.tinyupload.com/index.php?file_id=06135232736731778851

I guess it will be a few clicks away.

In the mean time, I'll update the DockerFile file (in this week).

Have a nice vacation!

**Comment by xie-dongping** [comment]
So the Dockerfile is updated and I have tested it with 
```
make server_cn
make results 
make server_cn
```
and then
```
make pdf-cn
```

All work without problems.

**Comment by xogeny** [comment]
I wonder if @dietmarw could find a way to add a webhook and integrate it into our CI system? :-)

**Comment by dietmarw** [comment]
@mtiller The problem is simply that compilation takes too long for what our drone.io account allows. So unless you provide some kind of alternative I'm not sure how to solve this.

**Comment by xogeny** [comment]
I was thinking of combining [this](https://github.com/xogeny/go-hooksink) with the Docker image that we have now.  In this sense, we could create our own service (outside drone.io) that would rebuild the book on commit.  My proposal, if we were to do this, would be to have a special branch like `public` or `published` or something that we use to commit to the "real" site.  But to also have a site like `draft.book.xogeny.com` that we publish `master` to.  The idea would be that everything committed to `master` would cause `draft.book.xogeny.com` to be updated.  Then, once we reviewed that, we could push to `published` which would update `book.xogeny.com`.

Thoughts?  I think most of the pieces are actually there.  The web hook just has to trigger `make` and we could pass the necessary credentials into the running Docker image using `-e` flags when we `run` it.

**Comment by xie-dongping** [comment]
IMO, the CI system is another issue. 

This issue can be resolved without the fully-fledged CI system with docker and the web hook. 


Nevertheless, I have added a new make target for a one step docker build in docker folder with PR #253.

I  have tested it with my own s3bucket. It should also work for publishing. Additional changes can be added to the text/build_all.sh

For web hook, I guess the script can already be plugged directly in the call back function.

**Comment by xogeny** [comment]
This is working now, isn't it?

**Comment by xie-dongping** [comment]
Yes, it is.
