### ISSUE TITLE
Solution for broken icon images needed

### ISSUE THREAD

**Issue by dietmarw** [xogeny/ModelicaBook#257]
The current way to create the images of the icons is by the help of the OMC internal script `share/doc/omc/testmodels/generate_icons.py`. The problem is that that script has not received much love and care lately. Even worse the output of that script changes over time and not in a good way.

At the same time OMEdit itself now renders the icons correctly. But according to @sjoelund that part of OMEdit can currently not be scripted (@adeas31 might perhaps have an idea how one could use that?). 

Now a workaround would be to generate the used Icon images manually with OMEdit and then add them to the repo. Those images don't change much anyway and the danger of breaking the output between `make` runs is also reduced. Of course it's no longer a nice fancy build process.

**Comment by xogeny** [comment]
I am in favor of manually creating the images once and for all.  They really don't change and I think quality images are important.  Whether we use OMEdit or any other tool that can output quality SVG does not matter to me.

The issue, for me at least, is finding the time to do this (at least before the conference).  But I just wanted to at least express my support for this and, obviously, my willingness to accept a pull request in this direction.

**Comment by dietmarw** [comment]
Looks like it's just 10 Icons. Let me prepare that PR.

**Comment by xogeny** [comment]
As I understand it, this addresses a bunch of icon images (and apparently addresses all of them).  But the issue with diagrams is still open, correct?

**Comment by dietmarw** [comment]
I think the diagrams are fine. I thought I checked.

**Comment by xogeny** [comment]
Alright in the sense that they are already SVG, yes.

I was thinking more about the sizing issues as seen in [this diagram](http://book.xogeny.com/components/subsystems/heat_transfer/).  The diagrams are too large.   But I'll open a separate issue since that is a fix to the markup (`:width:`).  I'm not sure why I made these so huge.
