### ISSUE TITLE
Can import constants as well!

### ISSUE THREAD

**Issue by HansOlsson** [xogeny/ModelicaBook#265]
In ModelicaBook/text/source/components/packages/importing.rst it states that you create an alias to a type. Typically it is a type (or other kind of class), but it is also possible to import a constant.

That can be solved by using 'name' instead of 'type'.

**Comment by dietmarw** [comment]
@HansOlsson could you make a PR out of  	d370f28 ?

**Comment by dietmarw** [comment]
@HansOlsson It looks like you fixed this several times in several isolated commits but never sent a PR. Correct?

**Comment by dietmarw** [comment]
@HansOlsson Btw, I can also create a PR using your already existing branch. Just let me know.

**Comment by dietmarw** [comment]
@HansOlsson I've created the PR on your behalf cherrypicking your commit. You might actually delete some of the orphan branches you have in your fork.
