### ISSUE TITLE
Add missing index references for import

### ISSUE THREAD

**Issue by dietmarw** [xogeny/ModelicaBook#273]
_From @xogeny on September 21, 2015 8:37_

There are three ways to `import` discussed in `text/source/components/packages/importing.rst` (normal, short hand, wildcard).  None of them appears in the index.  This is because [the markup to add an index entry](http://sphinx-doc.org/markup/misc.html#directive-index) is missing.  This should be added.  At a minimum, there should be at least one entry in the index pointing to this section of the book for more information about `import`.  Ideally, the discussion of each different type of import should be referenced distinctly (leading to three specialized index entries, one for each type of import).

_Copied from original issue: modelica2015/ModelicaBook#8_

**Comment by dietmarw** [comment]
This is related to #163 and was solved as part of Modelica 2015 tutorial in da4f2f8ebf1b08feda87632b5bd24ffb0a9937e1

**Comment by xogeny** [comment]
The mentioned commit isn't a hyperlink.  Is it correct?

**Comment by dietmarw** [comment]
I noticed that too and have no idea why auto linking does not work. You can check yourself: https://github.com/xogeny/ModelicaBook/commit/da4f2f8ebf1b08feda87632b5bd24ffb0a9937e1
