### ISSUE TITLE
Review Diagram Sizes

### ISSUE THREAD

**Issue by xogeny** [xogeny/ModelicaBook#274]
It seems as though many of the diagrams are overly large.  Now that we have proper SVGs, we should revisit the size of [these images](http://book.xogeny.com/components/subsystems/heat_transfer/) to make them more reasonable.

**Comment by dietmarw** [comment]
I agree.

**Comment by dietmarw** [comment]
The question is should we go for absolute size or relative (%) size.

**Comment by dietmarw** [comment]
I played a bit with sizes. It looks like for icons `:height: 200px` works fine and for diagrams `:width: 500px`. I'll wait for some feedback before doing any changes.

**Comment by dietmarw** [comment]
One problem though is that the PDF does ignore absolute widths but recognises width given in %. :frowning:

**Comment by xogeny** [comment]
My suggestion...for all figures, we add the following CSS rules:

```
.figure {
    max-width: 50%;
    min-width: 500px;
}
```

The `min-width` rule trumps the `max-width` rule so it basically means it will be no more than half the screen, but no less than 500 pixels.

**Comment by dietmarw** [comment]
I think that is a good start. Still need to see how to fix it for the PDF then.

**Comment by xogeny** [comment]
Note that I can use media queries in CSS to handle the `print` case differently from the `screen` case.  I've updated `xogeny_css.t` to include CSS rules for diagram and icon figures (settings are slightly different, as you suggested).  I've also duplicated the CSS rules at the end under a `print` media query.  That way, you can play specifically with the print settings and optimize them for ebook versions.

**Comment by xogeny** [comment]
I'm pretty happy with the results of this.  I've previewed it locally.  CI is pushing the new version out to `beta` now.
