### ISSUE TITLE
Get rid of early access and "hide" git release info

### ISSUE THREAD

**Issue by xogeny** [xogeny/ModelicaBook#276]
Currently, there is an "Early Access" banner on pages in the book.  We should get rid of this.

In addition, the git information is prominently displayed.  We should keep it on the page, but hide it somewhere so we can see find it but others won't really notice it.

**Comment by xie-dongping** [comment]
Maybe we can close this one?

**Comment by dietmarw** [comment]
Since the version info is now in the meta data field I actually like to see the git info like it used to be. By this I can see **exactly** which version is currently published without the normal user being disturbed by this "over information".

**Comment by xogeny** [comment]
Is there a proposal here?

**Comment by dietmarw** [comment]
Basically revert the version number to the old <version>-g-<hash> but leave it in the meta properties.

**Comment by xogeny** [comment]
Ah, agreed.  I didn't realize that was the case.  @xie-dongping can you use the `git describe` output for the metadata?

**Comment by xie-dongping** [comment]
@dietmarw  @xogeny 
I actually thought about that. And the version now does exactly that. 

The implementation now will should the `version-g<hash>` iff it is built directly from a branch. 

However, this version in the s3 bucket is built from a tag (by using `git checkout v0.4.0`). And in this case, since the result of 
```
$ git checkout v0.4.0
HEAD is now at d1345ba... Merge pull request #277 from xie-dongping/chinese_fix1
$ git describe HEAD
v0.4.0
```
is exactly `v0.4.0`, the commit hash is not there, (unlike the results you get in a branch).

**Comment by sjoelund** [comment]
You can use `git describe --long` if you always want the hash in there, but if it is indeed a tagged version, that should be OK to put in the meta properties as well, right?

Example (for OM):
```
$ git describe v1.9.2
v1.9.2
$ git describe --long v1.9.2
v1.9.2-0-g80b135d
$ common/semver.sh # [1]
v1.9.4-dev.104+gfed18df
```

OM tries to use git describe to produce a semantic version number based on the most recent annotated tag:
[1] [semver.sh](https://github.com/OpenModelica/OpenModelica-common/blob/d7e96410a8be73d31c312dcf42e920f5ed6ab2f3/semver.sh)

**Comment by dietmarw** [comment]
I think I would prefer the long version even if it is the actual tag. It's only in the metadata anyway :-)

**Comment by xie-dongping** [comment]
Done.

**Comment by dietmarw** [comment]
Thanks.
