### ISSUE TITLE
Bug redeclare with modifier in the base class

### ISSUE THREAD

**Issue by xie-dongping** [xogeny/ModelicaBook#294]
The new version of OpenModelica (1.9.4~dev-336-g168e406) reports the following errors:

```
[1] 19:25:40 Translation Error
[ModelicaByExample.Architectures.ThermalControl.Architectures.ExpandableArchitecture: 9:3-10:70]: Variable controller: In modifier (k = 20), class or component k not found in <ModelicaByExample.Architectures.ThermalControl.Implementations.OnOffControl$controller>.

[2] 19:25:41 Translation Error
Error occurred while flattening model ModelicaByExample.Architectures.ThermalControl.Examples.OnOffVariant
```

This is because that the base class ExpandableArchitecture uses  `Implementations.ExpandablePIControl` as `controller`, therefore the modifier `k=20` is valid. However, the model `OnOffVariant` `redeclare` the member `controller` as `Implementations.OnOffControl`, which doesn't have a parameter `k`.

**Comment by xie-dongping** [comment]
Additional [error logs from CI!](https://circleci.com/gh/modelica-projects/ModelicaBook/4)

**Comment by dietmarw** [comment]
@xie-dongping Could you update the docker settings to use the latest stable v1.9.6 of OM and check if it works. I didn't have any issue running the models.

**Comment by xie-dongping** [comment]
@dietmarw Do you mean the original models in xogeny/ModelicaBook/master? It seems that according to the discussions in the #295 the original implementation is not idiomatic and has to be modified to be using constrainedby anyway. 

I can update the docker image and see what happens.

**Comment by dietmarw** [comment]
I'm actually not sure tbh. But you could check if simply updating to the latest stable copes with this bug at least.

**Comment by xie-dongping** [comment]
So the newer stable can compile the master, but not still not the idiomatic implementation in `xie-dongping/ModelicaBook/modifier`.

In order to update and check the CI,  PR #317 should be merged or else the CircleCI continues to use the older base image book-om (openmodelica container).

**Comment by dietmarw** [comment]
OK I took the liberty of accepting #317. I hope that is fine with you @mtiller.

**Comment by xogeny** [comment]
So is this resolved?  I haven't noticed any issues with the new CI build system?

**Comment by dietmarw** [comment]
Hard to tell. You have now a different docker setup and I can not say for certain that the original reported error does no longer occur. OMC's error messages that (are still thrown) are hard to judge by if actual errors or warnings which can be safely ignored.

**Comment by dietmarw** [comment]
Just tested it with OMC v1.12.0 (which is also the one we use in the Docker image) and no more warnings are generated. So this can be closed.
