### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by xie-dongping** [xogeny/ModelicaBook#298]
The following tasks are still to be done for CI system:
* Create test criterion for a successful build
* Change the Makefile to enable customer bucket via environmental variables
* Set up a branch/fork for the release process + CI, since the build results now would be directly uploaded to the main bucket (which is not so good)

**Comment by xie-dongping** [comment]
The docker image runs smoothly in circleCI. Just a couple of PR (#295 #296 ) to be integrated in the main repo and I guess everything should be fine.

**Comment by xie-dongping** [comment]
I suppose that we can build and preview results in my bucket, and then mirror the whole site to the official one by using s3cmd periodically.

**Comment by xogeny** [comment]
Sounds good.  Looks like #295 is the main hold up.  Your most recent refactor looks good although I added a comment about updating the PR itself. Hopefully we'll hear something back from the OM guys about this. Obviously, the code in the book should follow the Modelica spec and not conform to peculiarities in OM. So we really need to resolve #295 correctly.

But I look forward to having the CI stuff functioning!

**Comment by xogeny** [comment]
What's the status on this?  I'd like to get to the point where we can a) auto-build and preview the current master at a public URL and b) auto-build and publish a branch version to book.xogeny.com.

It would be good to spell out exactly what still needs to be done and I can try and help move it along.

Thanks.

**Comment by xie-dongping** [comment]
@xogeny 
We can already theoretically [auto build](https://circleci.com/gh/modelica-projects/ModelicaBook/) and [preview it at a public url](http://cnbook.s3-website-ap-northeast-1.amazonaws.com/). It is just that the build fails. 

One of the problem is surely with PR #295 , I'll update the PR shortly and file a bug report in OpenModelica. Then after the bug fix, I'll have to update the docker image to include the newest version of OM. I've got a fever a few days ago, so no progress in the time, but I think I can do it this week. 

Other than that, I'll write a short script to copy the the s3bucket and give you list and write permission to my bucket.
