### ISSUE TITLE
Continuous Integration: the mirror repository is not updating

### ISSUE THREAD

**Issue by xie-dongping** [xogeny/ModelicaBook#318]
@dietmarw [Our mirror repository](https://github.com/modelica-projects/ModelicaBook) for continuous integration is lagging behind. Maybe the mirroring service is not working as planned?

**Comment by xie-dongping** [comment]
Sorry, I made a mistake.

**Comment by dietmarw** [comment]
Was just gonna say. It only gets updated once a day.
