### ISSUE TITLE
Updating to new sphinx versions

### ISSUE THREAD

**Issue by xie-dongping** [xogeny/ModelicaBook#326]
Due to bugs with an internationalized version we are now using the `sphinx 1.3`.

We should probably fix the bug for sphinx. (Maybe it is a problem with `sphinx-intl`)

**Comment by xie-dongping** [comment]
PR #324

**Comment by thorade** [comment]
Also see 
http://www.sphinx-doc.org/en/latest/changes.html
https://github.com/sphinx-doc/sphinx-intl/blob/master/CHANGES

**Comment by xogeny** [comment]
My understanding is that @dietmarw has tested the new build system against Sphinx 1.6.5 and things look good.  I'm waiting for him to confirm that everything (especially building ebooks) is working and then we can upgrade.  Note, with the new build system, changing the Sphinx version would be done by submitting a PR to the the [`book-builder` repository](https://github.com/xogeny/book-builder).  I'm hoping @dietmarw will do that once he finishes his checks.

**Comment by dietmarw** [comment]
We have now the system running stable with sphinx 1.6.5 (current ehh stable). @xie-dongping Perhaps you could take a look at the new improved build system and test it for the Chinese version again. I've already did some updates in the Makefile for the *_cn rules. Also we are now using xelatex for all print versions, not just the international ones.

**Comment by xogeny** [comment]
I'm closing this since the task itself is done.  Feel free to create a separate issue for whatever is going on with the Chinese language version.  Hopefully @xie-dongping will chime in soon...
