### ISSUE TITLE
commented out "Chemical Components" example do partially appear

### ISSUE THREAD

**Issue by pierre-haessig** [xogeny/ModelicaBook#342]
At the end of [System](https://github.com/xogeny/ModelicaBook/blob/master/text/source/components/components/chem_comps.rst#system) section of the "Chemical Components" chapter, there is a commented out plot in a todo. However, part of the commented out text do appears in the rendered page

> Simulating this system for 10 seconds yields the following concentration trajectories:
> # .. plot:: ../plots/ABX.py # :include-source: no

Oddly enough, it doesn't appear in the Github rendered rst.

**Comment by dietmarw** [comment]
This seems to be an issue with the older version of sphinx-build that was used to build the current online version. I've just rebuild it with sphinx-build 1.4.9 and the comment is rightly hidden. 

@xie-dongping What is the status on the "CI-build" version. Is that somewhere online so one could check that too?

**Comment by xie-dongping** [comment]
@dietmarw 
If i'm not mistaken, it doesn't seem to be apearing in the [CI build](http://cnbook.s3-website-ap-northeast-1.amazonaws.com/components/components/chem_comps/#system)

**Comment by dietmarw** [comment]
It does indeed not. So perhaps it's time to trigger a new push of the current version to book.xogeny.com, @mtiller?

**Comment by xogeny** [comment]
What is the process for pushing a new version from CI?  Presumably the CI version is built with new commits to master.  Is there a simple way to push the already generated CI version to book.xogeny.com?  Or do we have to do a build locally and use the scripts to update it?

**Comment by xie-dongping** [comment]
I haven't defined a proper release process for the release yet. So I guess
we can only do it locally now. Maybe later I can take some time to define
it properly.

Michael Tiller <notifications@github.com>于2016年10月14日周五 19:52写道：

**Comment by dietmarw** [comment]
OMC now supports the simulation of this model (see https://trac.openmodelica.org/OpenModelica/ticket/2572#comment:13)
