### ISSUE TITLE
Update ModelicaByExample to MSL v3.2.2

### ISSUE THREAD

**Issue by tbeu** [xogeny/ModelicaBook#355]
Should ModelicaByExample be updated to MSL 3.2.2? It is not needed by features, but just for avoiding to get left behind (one day, as with FirstBookExamples).

And because I am curious.
* ~~Do you plan to update the book before the Modelica Conference in Praha?~~
* It says, that version is 0.3.6.something and I also noticed the issues for milestone:0.5.0. What is your target to get 0.5.0 finished?

**Comment by xogeny** [comment]
I've put quite a bit of work this week into getting the build process stabilized.  I'm already pushing builds created by CircleCI out to http://beta.book.xogeny.com (if you care to take a look).

I would gladly accept a PR for this assuming:
    * It didn't create any unnecessarily white space changes (*i.e.,* only change the string literal, don't resave all the files from a tool)
    * Make sure it builds completely.  See the updated `README` for instructions on using the new (greatly simplified) build system.

**Comment by tbeu** [comment]
http://beta.book.xogeny.com/components/packages/msl/ speaks about Modelica.Constants v3.2.1. Note, that Modelica.Constants was updated with MSL 3.2.2.

**Comment by xogeny** [comment]
Apart from mentioning 3.2.2, is there any *other* change that has to be made?  (i.e., is the use of `Modelica.Constants` somehow different as a result of the change in 3.2.2?)

**Comment by tbeu** [comment]
Yes, the constants were updated itself. That's it basically.

**Comment by xogeny** [comment]
What I meant was...are there any changes needed to the book or the `ModelicaByExample` library (apart from updating the `uses` annotation)?  If so, list them so I know what changes are required.

**Comment by tbeu** [comment]
What I meant was the updated [Modelica.Constants](https://build.openmodelica.org/Documentation/Modelica.Constants.html)...not sure if you want to update the [book](http://beta.book.xogeny.com/components/packages/msl/#constants) to reflect these updated constants (and MSL release).

**Comment by xogeny** [comment]
@tbeu But I still have the same question...apart from the version number, is there something else you think needs updating?  Did the names of any constants change?  Did their values.  I don't know what, if anything, changed between 3.2.1 and 3.2.2 in the `Constants` package.  So if you know of any changes, please *list them*.  Otherwise, I will just update the number.

**Comment by tbeu** [comment]
Yes, the values and the descriptions were touched for MSL 3.2.2. See https://github.com/modelica/Modelica/commit/74a733cbf5676d799dd4d6c6f67a1a3040ad8837 and https://github.com/modelica/Modelica/commit/36f2eac72b0e0bec79dab790447a316f2fa42f3b.

**Comment by xogeny** [comment]
OK, I've made those updates.  You should see them with my next push.

**Comment by dietmarw** [comment]
0.5.0 is not released yet, right? So this fix would be part of it.

**Comment by xogeny** [comment]
True.  I will reassign.

**Comment by xogeny** [comment]
Oh, I see you already did.
