### ISSUE TITLE
Plots not loading properly in sensor comparison

### ISSUE THREAD

**Issue by xogeny** [xogeny/ModelicaBook#366]
In the published book, several figures are **missing**.  This appears to be due to an error fetching case data.  With the new React based approach, the original figures remain, but the interactivity is never added (slightly better).  The fix is to make sure the case data is present and that the interactive examples actually run (these are among the most interesting examples, so they really should be fixed!).

**Comment by dietmarw** [comment]
This is actually an ongoing issue that we don't get error messages about missing plots during build. In the past there were several plots (and probably still are) that were missing. And this normally is only spotted by accident when one finds a reference in the text to something that is not displayed. It would be nice if we could have some way to trigger a warning if an image (for whatever reason) is not included.

**Comment by xogeny** [comment]
I'm reasonably confident that, at this point, all the issues have been sorted out.  It was really an issue of correctly matching up the plot with the corresponding case data and executable.  I'm pretty sure it is sorted out and lots of figures render as interactive.  I'm closing this for now, but if you find more feel free to add an issue.
