### ISSUE TITLE
Annotation folding

### ISSUE THREAD

**Issue by xogeny** [xogeny/ModelicaBook#37]
I should find or create a script that will do annotation folding in the HTML listings.  If people don't have Javascript, then they just don't get the folding feature.  But if they do, then they should have some way to expand or collapse annotations (with the default being collapsed except possibly in sections where annotations are being specifically discussed).

**Comment by xogeny** [comment]
I wonder if we could do this with some React magic...

**Comment by xogeny** [comment]
I looked into this, and it seems like all that is required is to look for this string

```<span class="kr">annotation</span>```

as the starting point of an annotation and this string

```<span class="p">;</span>```

as the ending point.  From there, a simple `semantic-ui` accordion or similar CSS/JS component could be used to hide/show the annotation.

**Comment by xogeny** [comment]
I figured out a way to do this.  It works surprisingly well.  The default is to hide graphical annotations.

**Comment by dietmarw** [comment]
So all what is left now is to find a dynamic pdf version of this and of course a sokution for the paper version. I guess you need to talk to children book publishers. They have experience with this kind of thing :-D
