### ISSUE TITLE
Empty package ModelicaByExample.Architectures.SensorComparison.Architectures 

### ISSUE THREAD

**Issue by dietmarw** [xogeny/ModelicaBook#371]
`ModelicaByExample.Architectures.SensorComparison.Architectures "Different system architectures"`

Just saw that there is this empty package. What is the purpose? Was it perhaps simply forgotten?

**Comment by xogeny** [comment]
It looks to me like I put the different architectures in `ModelicaByExample.Architectures.SensorComparison.Examples`.  So I'll remove this.  I don't think anything references this.
