### ISSUE TITLE
Hyst_Q application not working

### ISSUE THREAD

**Issue by xogeny** [xogeny/ModelicaBook#375]
See http://beta.book.xogeny.com/behavior/discrete/hysteresis/

**Comment by xogeny** [comment]
Same is true for CC1_Q on same page.  I suspect it has something to do with cases that apply `mods`.

**Comment by xogeny** [comment]
CC1 has chattering so it results in lots of data.  Perhaps not a good idea to make it interactive...

**Comment by dietmarw** [comment]
See also #104

**Comment by xogeny** [comment]
Yep, precisely why I was investigating this.

**Comment by xogeny** [comment]
This issue is primarily because each figure in the book has a unique id (*e.g.,* `CC1`).  For the most part, the *executable* that generated the results for the figure has the same id...but not always.  It is for the cases where there are multiple plots that share an executable that we run into problems and this is because the ids are used interchangeably in contexts where they should not.

**Comment by xogeny** [comment]
OK. I fixed the code in the server that was confused on this point.  I don't have a complete list of "problem" plots, but I tested the new server image with many plots where this was an issue before and it has been resolved.  As a result, many more plots are fully interactive now. :tada:
