### ISSUE TITLE
Some plots not interactive

### ISSUE THREAD

**Issue by xogeny** [xogeny/ModelicaBook#386]
The `SRLCv` and `SRLCi` plots in the section on [discrete switching](http://beta.book.xogeny.com/behavior/discrete/switching/) are missing.

**Comment by xogeny** [comment]
Doh!  Turns out using SVGs broke my interactive plots (it was extracting plot id from image name).  I need to fix this before 0.5.0.

**Comment by dietmarw** [comment]
Yes I noticed that interactive was no longer working. Sorry for this enhancement that broke everything :-/

**Comment by xogeny** [comment]
They are back now.  It was a simple fix.

**Comment by dietmarw** [comment]
The Harmonic pendulum is not interactive yet. 
http://beta.book.xogeny.com/components/subsystems/pendulums/
On purpose?
