### ISSUE TITLE
Published HTML version is missing crucial version meta information

### ISSUE THREAD

**Issue by dietmarw** [xogeny/ModelicaBook#396]
When building the HTML locally all pages contain the meta tag 
```html
<meta name="description" content="Release v0.4.0-658-g9f007eb"> 
```
However looking at (beta.)book.xogeny.com that information is gone. It is quite important to know which version is actually running on the server and hence we added that meta field. I'm not sure why it is stripped out on the server version and how.

**Comment by xogeny** [comment]
Huh...not sure how it got lost.  I might be able to add it easily...I'll have to look into it.  But you know the version information is actually in the HTML (look at the lower right corner of the landing page).

**Comment by dietmarw** [comment]
Ah right, didn't know it was there. But still would be nice to be able to quick check on the individual pages.

**Comment by xogeny** [comment]
This will come out tagged as `v0.5.1`.
