### ISSUE TITLE
Scaled logo.png of sponsors on root-page.html

### ISSUE THREAD

**Issue by tbeu** [xogeny/ModelicaBook#63]
It is always a bad idea to down-scale the images in browser (by using the width attribute) as the resulting images often look poor. You better should use poperly scaled images instead, i.e. use with width=100%.

![sponsors](https://cloud.githubusercontent.com/assets/5444067/2614469/bf1c39f8-bbe7-11e3-9b05-544e526cef21.png)

**Comment by dietmarw** [comment]
The new version looks now like this and I think that is good enough.

![image](https://user-images.githubusercontent.com/9332/32905073-46336988-caf9-11e7-98c4-de29a7f5d8d7.png)
