### ISSUE TITLE
HierarchicalSystem_Variant1 missing sample_rate

### ISSUE THREAD

**Issue by xogeny** [xogeny/ModelicaBook#65]
Model 5: ModelicaByExample.Architectures.SensorComparison.Examples.HierarchicalSystem_Variant1
Information In sensor.sample_rate
The parameter sensor.sample_rate has no value. For simulation the value Modelica.Constants.eps from min attribute is used.

**Comment by dietmarw** [comment]
Commit contained wrong reference. Should have been #67 Hence reopening.
