### ISSUE TITLE
HysteresisEmbeddedControl issue with computeHeat function

### ISSUE THREAD

**Issue by xogeny** [xogeny/ModelicaBook#69]
Model 68: ModelicaByExample.Functions.ImpureFunctions.HysteresisEmbeddedControl
Error In ModelicaByExample.Functions.ImpureFunctions.HysteresisEmbeddedControl
Q=computeHeat(T,Tbar,Qcapacity);
^---

Unknown function "computeHeat" referenced.

**Comment by tbeu** [comment]
ModelicaByExample states that it uses Modelica 3.2.1 (that is based on MLS 3.2) but impure functions are a MLS 3.3 language element. Since there still is no Modelica 3.3 library :unamused: the simplest way to resolve the version conflict is to remove the explicit 3.2.1 version.

**Comment by sjoelund** [comment]
MSL version is unrelated to Modelica language spec version :smiley: You need a different annotation to determine which language spec a library uses. But the spec does not have any such annotations. Maybe we will in 3.4...

**Comment by tbeu** [comment]
MSL version is unrelated to Modelica language spec version? No, not true.

**Comment by sjoelund** [comment]
* MSL version used by a library is unrelated to the Modelica spec version used by the library.

**Comment by tbeu** [comment]
How can this be possible if the MSL version itself is related to the Modelica spec version?

**Comment by harmanpa** [comment]
If only: https://trac.modelica.org/Modelica/ticket/643

**Comment by tbeu** [comment]
Thanks Peter for pointing to [#643](https://trac.modelica.org/Modelica/ticket/643). Was not aware of this. So Martin is right with 3.4...

**Comment by harmanpa** [comment]
That ticket is only 3 years old so we might reach a consensus in 1 or 2
years ;-)

**Comment by tbeu** [comment]
Yes, it is tedious as ever. Same pitfall as your reasoning there: Modelica_Synchronous uses language features from the 3.3 specification, but it depends on Modelica 3.2.1
