### ISSUE TITLE
Consider adding start attributes to these models...

### ISSUE THREAD

**Issue by xogeny** [xogeny/ModelicaBook#71]
Model 71: ModelicaByExample.Functions.Interpolation.IntegrateInterpolatedVector
Warning In ModelicaByExample.Functions.Interpolation.IntegrateInterpolatedVector
There is no start attribute of state z. It is set to 0.
Model 75: ModelicaByExample.BasicEquations.SimpleExample.FirstOrderDocumented
Warning In ModelicaByExample.BasicEquations.SimpleExample.FirstOrderDocumented
There is no start attribute of state x. It is set to 0.
Model 76: ModelicaByExample.BasicEquations.SimpleExample.FirstOrder
Warning In ModelicaByExample.BasicEquations.SimpleExample.FirstOrder
There is no start attribute of state x. It is set to 0.

**Comment by dietmarw** [comment]
I was thinking to "fix" this just like I did in #67. Problem is that some of the models here are placed in the book **very** early on. Adding then a construct like `(fixed=true, start=0)` will be quite confusing as nothing about this was mentioned in the book to that point.

So what to do? Leave the models as they are and rather accept a warning?

**Comment by xogeny** [comment]
If they are early in the book (before `fixed` is discussed), we should leave them alone.  I tried to be very careful with the examples to introduce language constructs gradually.

**Comment by dietmarw** [comment]
In this case I'll rather leave them as they are and accept warnings from the tool.
