### ISSUE TITLE
sliding TOC doesn't slide

### ISSUE THREAD

**Issue by thorade** [xogeny/ModelicaBook#74]
With Firefox 28 the sliding TOC menu does not slide out when the address has an anchor.

This happens after following any link with anchor: 
http://beta.book.xogeny.com/components/packages/nimport/#importing-physical-types 
http://beta.book.xogeny.com/behavior/equations/physical/#physical-types
while on 
http://beta.book.xogeny.com/components/packages/nimport/
http://beta.book.xogeny.com/behavior/equations/physical/
the sliding TOC works just fine.

**Comment by xogeny** [comment]
Is this still an issue with [beta](http://beta.book.xogeny.com)?  The handling of this is slightly different now.

**Comment by thorade** [comment]
I cannot reproduce it anymore, so it seems to be fixed. Thanks!
