### ISSUE TITLE
source code 403 forbidden

### ISSUE THREAD

**Issue by thorade** [xogeny/ModelicaBook#76]
For quite a lor of examples, I cannot view the source code, but instead get a 403 forbidden error. 

It works in the first couple of chapters, e.g. here:
http://beta.book.xogeny.com/behavior/equations/first_order/
but fails in the later chapters, e.g. here 
http://beta.book.xogeny.com/components/components/rot_comps_adv/

**Comment by dietmarw** [comment]
Tested this with sphinx-build 1.4.8 and it seems to have been fixed upstream: https://github.com/sphinx-doc/sphinx/issues/1452
