### ISSUE TITLE
Advanced Topics

### ISSUE THREAD

**Issue by thorade** [xogeny/ModelicaBook#77]
So far, `stream` variables/connectors are not mentioned at all in the book.
https://www.google.de/search?q=site%3Abeta.book.xogeny.com+stream
Maybe these could be discussed in the Advanced Topics chapter.

**Comment by Satinelamp** [comment]
`Stream variable` is very confusing, the only appropriate material might be the original paper of `Stream connector`.
https://pdfs.semanticscholar.org/8fb3/aae2ce09475908165a809019ee14f0b78135.pdf
https://build.openmodelica.org/Documentation/Modelica%203.2.3/Resources/Documentation/Fluid/Stream-Connectors-Overview-Rationale.pdf
