### ISSUE TITLE
Identifier after trailing end not properly highlighted

### ISSUE THREAD

**Issue by xogeny** [xogeny/ModelicaBook#8]
I seem to recall discussing this with @dietmarw and playing around with potential solutions.  But I forget what I managed to achieve.  It would be good to fix the highlighter for Modelica so it did this correctly though.

**Comment by dietmarw** [comment]
@mtiller can you give an example. I guess it is probably already fixed upstream but without a test case it is hard to tell.

**Comment by xogeny** [comment]
I'm not sure what the issue was, but I don't see it now.
