### ISSUE TITLE
SVG files

### ISSUE THREAD

**Issue by tbeu** [xogeny/ModelicaBook#85]
Some issues with SVGs
- [x] 1. E.g. http://beta.book.xogeny.com/components/architectures/sensor_comparison/ embeds FlatSystem.svg which is far too large on (my) screen.
- [x] 2. If - on above site - I zoom in Firefox 28.0 with CTRL key plus mouse wheel the svg image remains at its large size wheras text zooms in or out.
- [x] 3. E.g. there are two small red squares near damper and springDamper in FlatSystem.svg that should not be there. In fact many SVG files have those red squares.
- [ ] 4. Many SVGs have dummy title `<title>OMEdit - OpenModelica Connection Editor</title>` only.
- [x] 5. Block trapezoid of FlatSystem.svg displays period=%period but should display the real period (1.0) here.

**Comment by johanrhodin** [comment]
In addition to the dummy titles, there are also dummy descriptions that should be changed. <desc>Generated by OMEdit - OpenModelica Connection Editor</desc>. I'd assumed that would be good for SEO and such.

**Comment by dietmarw** [comment]
@johanrhodin what exactly do you mean. That you do NOT want the OMEdit title?

**Comment by johanrhodin** [comment]
@dietmarw Yes, instead of:
```
<title>OMEdit - OpenModelica Connection Editor</title>
<desc>Generated by OMEdit - OpenModelica Connection Editor</desc>

```
it should be
````
<title>Flat System</title>
<desc>Plant model with sensor</desc>
```

**Comment by dietmarw** [comment]
OK. I wonder where anyone would ever see that, though.

**Comment by johanrhodin** [comment]
It would be "to aid readers using assistive technologies." [http://www.idpf.org/accessibility/guidelines/content/svg/desc.php](http://www.idpf.org/accessibility/guidelines/content/svg/desc.php)

**Comment by dietmarw** [comment]
Right. PR welcome :-D

**Comment by dietmarw** [comment]
I'm closing this now. If someone wants to add the SVG tags then PRs are welcome.
