### ISSUE TITLE
Browser simulation of Architectures.SensorComparison.Examples.Variant1_unstable

### ISSUE THREAD

**Issue by tbeu** [xogeny/ModelicaBook#86]
Are parameters like state_select, useHeatPort, useSupport or phi_nominal really supported by browser simulation? In general: Are enumerations and booleans supported? If not, those parameters should be hidden from reader. Unfortunately I cannot simulate this model in Firefox 28 since Simulating... button does never finish.

**Comment by xogeny** [comment]
Browser simulation is no longer supported.  But I do see that the `n` parameter in the 1D heat transfer model is still present.  I've created #360 to note that.

Does the unstable model appear in the book?  I couldn't find it.  I'm closing now.  But if there is an issue with running any of the examples in the book, please open an issue for them (along with a URL so I know precisely which one).
